export default function mapCampaignToCandidate(campaign) {
  if (!campaign) {
    return false
  }
  const {
    slug,
    details,
    campaignPlan,
    goals,
    pathToVictory,
    color,
    image,
    twitter,
    instagram,
    facebook,
    linkedin,
    tiktok,
    snap,
    twitch,
    hashtag,
    website,
    customIssues,
    endorsements,
    launchStatus,
    lastVisited,
  } = campaign
  const {
    firstName,
    lastName,
    party,
    otherParty,
    state,
    office,
    officeTermLength,
    otherOffice,
    pastExperience,
    occupation,
    funFact,
    district,
    city,
    filedStatement,
    campaignCommittee,
    pledged,
    knowRun,
    primaryElectionDate,
  } = details || {}
  const { slogan, aboutMe, why } = campaignPlan || {}

  const { electionDate } = goals || {}

  const { voteGoal, voterProjection } = pathToVictory || {}
  return {
    slug,
    firstName,
    lastName,
    party: party === 'Other' ? otherParty : party,
    state,
    office,
    officeTermLength,
    otherOffice,
    slogan,
    about: aboutMe,
    why,
    pastExperience,
    occupation,
    funFact,
    voteGoal: parseInt(voteGoal) || 0,
    voterProjection: parseInt(voterProjection) || 0,
    color,
    image,
    twitter,
    instagram,
    facebook,
    linkedin,
    tiktok,
    snap,
    twitch,
    hashtag,
    website,
    district,
    city,
    customIssues,
    endorsements,
    launchStatus,
    lastVisited,
    filedStatement,
    campaignCommittee,
    primaryElectionDate,
    electionDate,
    pledged,
    knowRun,
  }
}
