interface RedirectList {
  'how-to-run-for-mayor-in-santa-ana-california': boolean
  'how-to-run-for-treasurer-in-escondido-california': boolean
  'how-to-run-for-city-council-in-santa-clarita-california': boolean
  'how-to-run-for-mayor-in-elk-grove-california': boolean
  '10-steps-to-run-for-mayor-in-san-jose-california': boolean
  'how-to-run-for-city-clerk-in-santa-clara-california': boolean
  '10-steps-to-run-for-city-council-in-sunnyvale-california': boolean
  'how-to-run-for-city-clerk-in-antioch-california': boolean
  'how-to-run-for-city-council-in-glendale-california': boolean
  'how-to-run-for-city-clerk-in-fairfield-california': boolean
  '10-steps-to-run-for-treasurer-in-corona-california': boolean
  'how-to-run-for-mayor-in-fresno-california': boolean
  '10-steps-to-run-for-treasurer-in-vacaville-california': boolean
  'how-to-run-for-mayor-in-salinas-california': boolean
  'how-to-run-for-city-council-in-oakland-california': boolean
  'how-to-run-for-mayor-in-berkeley-california': boolean
  'how-to-run-for-mayor-in-sacramento-california': boolean
  'how-to-run-for-mayor-in-pomona-california': boolean
  'how-to-run-for-city-council-in-hayward-california': boolean
  'how-to-run-for-city-council-in-lancaster-california': boolean
  'how-to-run-for-city-council-in-riverside-california': boolean
  'how-to-run-for-treasurer-in-oxnard-california': boolean
  'how-to-run-for-city-council-in-irvine-california': boolean
  'why-you-should-run-for-office-in-portland-in-2023': boolean
  '5-reasons-why-you-should-run-for-nashville-city-council': boolean
  'why-you-should-run-for-office-as-an-independent-in-durham-in-2023': boolean
  'guide-to-early-voting-in-nashville': boolean
  'top-issues-facing-voters-durham-nc': boolean
  '4-reasons-why-you-should-run-for-city-council-in-memphis': boolean
  '5-reasons-why-you-should-run-for-city-council-in-charlotte': boolean
  '5-reasons-why-you-should-run-for-state-house-in-louisiana': boolean
  'charlotte-nc-politics': boolean
  'louisiana-elections': boolean
  'why-nashvilles-election-matters': boolean
  'nashville-low-voting-turnout': boolean
  'sidewalks-issue-nashville': boolean
  'durham-voter-turnout-trends': boolean
  'early-voting-durham-nc': boolean
  'constitutional-qualifications-to-run-for-president': boolean
  '10-effective-political-fundraising-ideas': boolean
  'how-to-run-for-county-legislature': boolean
  'run-as-independent-hawaii-2024': boolean
  'election-2024-launch-independent-campaign-ohio': boolean
  'election-2024-start-independent-campaign-north-carolina': boolean
  'election-2024-run-for-office-montana': boolean
  '20-reasons-you-should-run-independent-2024': boolean
  'independent-campaign-south-dakota-2024': boolean
  'election-2024-independent-campaign-washington': boolean
  'best-campaign-software-2023': boolean
  '2024-start-independent-campaign-arizona': boolean
  '10-reasons-independent-campaign-oklahoma-2024': boolean
  'absentee-voting-durham-nc': boolean
  'understanding-maines-state-legislature': boolean
  'running-as-an-independent-candidate-in-nashville': boolean
  'nashvilles-top-issues': boolean
  'los-angeles-city-council-district-6': boolean
  'how-to-find-ward-precinct-durham': boolean
  'goodparty-org-discord-community-launches-new-volunteer-teams': boolean
  '10-things-good-partys-discord': boolean
  'volunteer-spotlight-sal-davis-discord': boolean
  'volunteer-spotlight-join-goodparty-org-writing-team': boolean
  'volunteer-spotlight-join-goodparty-org-visibility-team': boolean
  'volunteer-spotlight-join-goodparty-org-politico-team': boolean
  'volunteer-spotlight-join-goodparty-org-design-team': boolean
  'volunteer-spotlight-join--goodparty-org-voter-outreach-team': boolean
  'guide-voter-registration-durham': boolean
  'campaign-management-consulting-services-for-independent-politicians': boolean
  'running-as-an-independent-in-tennessee': boolean
  'independent-candidates-running-in-north-carolina': boolean
  'the-rise-of-the-entitlement-of-the-thin-skinned-modern-politician': boolean
  'the-destructive-threat-oppenheimer-warns-us-about-isnt-nuclear-bombs-its': boolean
  'threads-doesnt-want-news-and-politics-on-its-platform-and-thats-a-huge': boolean
  'tackling-voter-apathy-engaging-and-empowering-younger-voters': boolean
  'how-to-craft-a-compelling-message-for-your-independent-campaign': boolean
  'free-tools-for-candidates': boolean
  'ai-tools-for-running-a-successful-independent-political-campaign': boolean
  'social-media-and-politics-why-it-matters-6-tips-for-campaigns': boolean
  'good-party-academy-what-to-expect': boolean
  'raising-the-bar-best-practices-for-political-fundraising': boolean
  'how-to-raise-funds-as-an-independent': boolean
  'understanding-independent-voters-their-impact-on-american-politics': boolean
  'how-to-get-on-ballot-independent-2024': boolean
}

const redirectList: RedirectList = {
  'how-to-run-for-mayor-in-santa-ana-california': true,
  'how-to-run-for-treasurer-in-escondido-california': true,
  'how-to-run-for-city-council-in-santa-clarita-california': true,
  'how-to-run-for-mayor-in-elk-grove-california': true,
  '10-steps-to-run-for-mayor-in-san-jose-california': true,
  'how-to-run-for-city-clerk-in-santa-clara-california': true,
  '10-steps-to-run-for-city-council-in-sunnyvale-california': true,
  'how-to-run-for-city-clerk-in-antioch-california': true,
  'how-to-run-for-city-council-in-glendale-california': true,
  'how-to-run-for-city-clerk-in-fairfield-california': true,
  '10-steps-to-run-for-treasurer-in-corona-california': true,
  'how-to-run-for-mayor-in-fresno-california': true,
  '10-steps-to-run-for-treasurer-in-vacaville-california': true,
  'how-to-run-for-mayor-in-salinas-california': true,
  'how-to-run-for-city-council-in-oakland-california': true,
  'how-to-run-for-mayor-in-berkeley-california': true,
  'how-to-run-for-mayor-in-sacramento-california': true,
  'how-to-run-for-mayor-in-pomona-california': true,
  'how-to-run-for-city-council-in-hayward-california': true,
  'how-to-run-for-city-council-in-lancaster-california': true,
  'how-to-run-for-city-council-in-riverside-california': true,
  'how-to-run-for-treasurer-in-oxnard-california': true,
  'how-to-run-for-city-council-in-irvine-california': true,
  'why-you-should-run-for-office-in-portland-in-2023': true,
  '5-reasons-why-you-should-run-for-nashville-city-council': true,
  'why-you-should-run-for-office-as-an-independent-in-durham-in-2023': true,
  'guide-to-early-voting-in-nashville': true,
  'top-issues-facing-voters-durham-nc': true,
  '4-reasons-why-you-should-run-for-city-council-in-memphis': true,
  '5-reasons-why-you-should-run-for-city-council-in-charlotte': true,
  '5-reasons-why-you-should-run-for-state-house-in-louisiana': true,
  'charlotte-nc-politics': true,
  'louisiana-elections': true,
  'why-nashvilles-election-matters': true,
  'nashville-low-voting-turnout': true,
  'sidewalks-issue-nashville': true,
  'durham-voter-turnout-trends': true,
  'early-voting-durham-nc': true,
  'constitutional-qualifications-to-run-for-president': true,
  '10-effective-political-fundraising-ideas': true,
  'how-to-run-for-county-legislature': true,
  'run-as-independent-hawaii-2024': true,
  'election-2024-launch-independent-campaign-ohio': true,
  'election-2024-start-independent-campaign-north-carolina': true,
  'election-2024-run-for-office-montana': true,
  '20-reasons-you-should-run-independent-2024': true,
  'independent-campaign-south-dakota-2024': true,
  'election-2024-independent-campaign-washington': true,
  'best-campaign-software-2023': true,
  '2024-start-independent-campaign-arizona': true,
  '10-reasons-independent-campaign-oklahoma-2024': true,
  'absentee-voting-durham-nc': true,
  'understanding-maines-state-legislature': true,
  'running-as-an-independent-candidate-in-nashville': true,
  'nashvilles-top-issues': true,
  'los-angeles-city-council-district-6': true,
  'how-to-find-ward-precinct-durham': true,
  'goodparty-org-discord-community-launches-new-volunteer-teams': true,
  '10-things-good-partys-discord': true,
  'volunteer-spotlight-sal-davis-discord': true,
  'volunteer-spotlight-join-goodparty-org-writing-team': true,
  'volunteer-spotlight-join-goodparty-org-visibility-team': true,
  'volunteer-spotlight-join-goodparty-org-politico-team': true,
  'volunteer-spotlight-join-goodparty-org-design-team': true,
  'volunteer-spotlight-join--goodparty-org-voter-outreach-team': true,
  'guide-voter-registration-durham': true,
  'campaign-management-consulting-services-for-independent-politicians': true,
  'running-as-an-independent-in-tennessee': true,
  'independent-candidates-running-in-north-carolina': true,
  'the-rise-of-the-entitlement-of-the-thin-skinned-modern-politician': true,
  'the-destructive-threat-oppenheimer-warns-us-about-isnt-nuclear-bombs-its': true,
  'threads-doesnt-want-news-and-politics-on-its-platform-and-thats-a-huge': true,
  'tackling-voter-apathy-engaging-and-empowering-younger-voters': true,
  'how-to-craft-a-compelling-message-for-your-independent-campaign': true,
  'free-tools-for-candidates': true,
  'ai-tools-for-running-a-successful-independent-political-campaign': true,
  'social-media-and-politics-why-it-matters-6-tips-for-campaigns': true,
  'good-party-academy-what-to-expect': true,
  'raising-the-bar-best-practices-for-political-fundraising': true,
  'how-to-raise-funds-as-an-independent': true,
  'understanding-independent-voters-their-impact-on-american-politics': true,
  'how-to-get-on-ballot-independent-2024': true,
}

export default redirectList
